algo = input('Digite algo: ')

print('O tipo primitivo desse valor é:', type(algo))
print('Só tem espaços: ', algo.isspace())
print('É somente numeros:', algo.isnumeric())
print('É somente letras:', algo.isalpha())
print('É um alfanumerico:', algo.isalnum())
print('Está so com letras mainúsculas', algo.islower())
print('Está só com letras maiúsculas', algo.isupper())
print('Está capitalizada: ', algo.istitle())